image:
  repository: jayaraj0781/resilient-async-job-processing-platform-backend
  tag: "1.0.3"
  pullPolicy: IfNotPresent
backend:
  port: 5001
  resources:
    limits:
      cpu: "1"
      memory: "512Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3
postgres:
  image: postgres:16-alpine
  host: postgres
  port: 5432
  database: notifications
  secretName: resilient-postgres-secret
  resources:
    limits:
      cpu: "1"
      memory: "512Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3
  storage:
    size: 5Gi
redis:
  image: redis:7-alpine
  host: redis
  port: 6379
  resources:
    limits:
      cpu: "1"
      memory: "512Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"
  livenessProbe:
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3
minio:
  image: minio/minio:latest
  host: minio
  port: 9000
  consolePort: 9001
  region: us-east-1
  useSSL: false
  inputBucket: resilient-async-job-processing-inputs
  outputBucket: resilient-async-job-processing-outputs
  secretName: resilient-minio-secret
  accessKey: minioadmin
  secretKey: minioadmin
  rootUser: minioadmin
  rootPassword: minioadmin
  resources:
    limits:
      cpu: "1"
      memory: "512Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3
  storage:
    size: 5Gi
worker:
  resources:
    limits:
      cpu: "1"
      memory: "512Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"
mailtrap:
  enabled: true
  secretName: resilient-mailtrap-secret
  useSandbox: true
  inboxId: "4366358"
  senderEmail: hello@demomailtrap.co
  senderName: Resilient-Job-Platform
frontend:
  image:
    repository: jayaraj0781/resilient-async-job-processing-platform-frontend
    tag: "1.0.2"
    pullPolicy: IfNotPresent
  replicas: 1
  service:
    type: NodePort # Change to NodePort or LoadBalancer to expose externally
    port: 3000
    nodePort: 30080
  resources:
    limits:
      cpu: "500m"
      memory: "256Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"
  livenessProbe:
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3
serviceAccount:
  create: true
  name: service-account
