apiVersion: v1
kind: Service
metadata:
  name: {{ include "resilient-platform.fullname" . }}-frontend
  labels:
    {{- include "resilient-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type | default "NodePort" }}
  selector:
    {{- include "resilient-platform.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.frontend.service.port | default 3000 }}
      targetPort: 3000
      {{- if eq (.Values.frontend.service.type | default "NodePort") "NodePort" }}
      # nodePort 30080 makes the UI reachable at http://<node-ip>:30080
      nodePort: {{ .Values.frontend.service.nodePort | default 30080 }}
      {{- end }}
