apiVersion: v1
kind: Service
metadata:
  name: {{ include "resilient-platform.fullname" . }}-{{ .Values.minio.host }}-service
  labels:
    {{- include "resilient-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "resilient-platform.fullname" . }}-{{ .Values.minio.host }}
spec:
  type: ClusterIP
  selector:
    {{- include "resilient-platform.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "resilient-platform.fullname" . }}-{{ .Values.minio.host }}
  ports:
    - name: {{ include "resilient-platform.fullname" . }}-{{ .Values.minio.host }}-api
      port: {{ .Values.minio.port }}
      targetPort: {{ .Values.minio.port }}
    - name: {{ include "resilient-platform.fullname" . }}-{{ .Values.minio.host }}-console
      port: {{ .Values.minio.consolePort }}
      targetPort: {{ .Values.minio.consolePort }}
      protocol: TCP