apiVersion: v1
kind: Service
metadata:
  name: {{ include "resilient-platform.fullname" . }}-{{ .Values.redis.host }}-service
  labels:
    {{- include "resilient-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "resilient-platform.fullname" . }}-{{ .Values.redis.host }}
spec:
  type: ClusterIP
  selector:
    {{- include "resilient-platform.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "resilient-platform.fullname" . }}-{{ .Values.redis.host }}
  ports:
    - name: {{ include "resilient-platform.fullname" . }}-{{ .Values.redis.host }}
      port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}
      protocol: TCP