apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "resilient-platform.fullname" . }}-redis
  labels:
    {{- include "resilient-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  serviceName: redis-service
  replicas: 1
  selector:
    matchLabels:
      {{- include "resilient-platform.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        {{- include "resilient-platform.labels" . | nindent 8 }}
        app.kubernetes.io/component: redis
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          ports:
            - containerPort: 6379
