apiVersion: v1
kind: Secret
metadata:
  name: {{ include "resilient-platform.fullname" . }}-secrets
  labels:
    {{- include "resilient-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.user }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password }}

  S3_ACCESS_KEY: {{ .Values.minio.accessKey }}
  S3_SECRET_KEY: {{ .Values.minio.secretKey }}

  MINIO_ROOT_USER: {{ .Values.minio.rootUser }}
  MINIO_ROOT_PASSWORD: {{ .Values.minio.rootPassword }}

  MAILTRAP_API_KEY: {{ .Values.mailtrap.apiKey }}
