apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "resilient-platform.fullname" . }}-service-account
  labels:
    {{- include "resilient-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: service-account
