apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "resilient-platform.fullname" . }}-worker
  labels:
    {{- include "resilient-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "resilient-platform.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "resilient-platform.labels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      serviceAccountName: {{ include "resilient-platform.fullname" . }}-{{ .Values.serviceAccount.name }}
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - python
            - -m
            - app.workers.worker
          ports:
            - name: metrics
              containerPort: 8000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "resilient-platform.fullname" . }}-config
            - secretRef:
                name: {{ .Values.postgres.secretName }}
            - secretRef:
                name: {{ .Values.mailtrap.secretName }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }} 
